# fly.toml file generated for little-cloud-7161 on 2023-03-31T10:49:23+03:00

app = "little-cloud-7161"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
primary_region = "arn"
processes = []

[build]
  builder ="paketobuildpacks/builder:base"

[env]
  PORT ="5000"

[[services]]
  internal_port = 5000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
   
 
